# Dockerfile.backend
FROM python:3.11-slim

WORKDIR /app

COPY ./backend /app

RUN pip install --no-cache-dir -r requirements.txt && apt-get update && apt-get install -y dnsutils whois && adduser --disabled-password odin

USER odin

EXPOSE 5000

CMD ["gunicorn", "-w", "4", "-b", "0.0.0.0:5000", "dns_anal_back:app"]
