services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: backend
    hostname: backend
    ports:
      - "5000:5000"
      - "5678:5678"
    volumes:
      - ./backend:/app
      - uploads:/data/uploads
      - results:/data/results
    environment:
      - FLASK_ENV=development
    restart: always

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: frontend
    hostname: frontend
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/app
      - uploads:/data/uploads
      - results:/data/results
    depends_on:
      - backend
    restart: always

volumes:
  uploads:
  results: